apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmqbroker-pvc
  namespace: your-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi   # must match PV or less
  volumeName: rmqbroker-pv   # force bind to our manual PV
  storageClassName: ""
